[package]
name = "invgen"
version = "0.1.0"
authors = ["Elliott Minns <elliott.minns@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33"
git2 = "^0.10"
